#!/bin/bash

set -e

echo "=> Creating custom builder..."
docker buildx create --name custom-builder --use

echo "=> Custom build hook running"
docker buildx build \
  --builder custom-builder \
  --cache-from type=registry,ref=$DOCKER_REPO:cache \
  --cache-to type=registry,ref=$DOCKER_REPO:cache,mode=max \
  --platform linux/amd64,linux/arm64 \
  -t $IMAGE_NAME .

echo "=> Removing custom builder..."
docker buildx rm custom-builder || true